export ACR_SERVER=i77tddxe3v5lw.azurecr.io
export USERDOMAIN=MAGENIC
export OS=Windows_NT
export COMMONPROGRAMFILES=C:\Program Files\Common Files
export DELIVERY_INGRESS_TLS_SECRET_NAME=delivery-ingress-tls
export PROCESSOR_LEVEL=6
export PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules;C:\Program Files (x86)\Microsoft SQL Server\150\Tools\PowerShell\Modules\
export CommonProgramW6432=C:\Program Files\Common Files
export INGRESS_LOAD_BALANCER_IP=20.75.108.93
export CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
export HELM_CHARTS=.//charts
export MODEL=3560
export MSYSTEM_CARCH=x86_64
export DISPLAY=needs-to-be-defined
export WORKFLOW_ID_NAME=dev-wf
export SP_APP_ID=06d5bd5c-580e-414a-934a-3f9611cf60ad
export COSMOSDB_NAME=dev-d-nopqttanbbbi2
export HOSTNAME=gillese11
export PUBLIC=C:\Users\Public
export OLDPWD=/
export CONFIG_SITE=/etc/config.site
export IDENTITIES_DEPLOYMENT_NAME=azuredeploy-prereqs-1620258603816714800-dev-identities
export EXEPATH=C:\Program Files\Git
export TEST=SSH_PUBLIC_KEY_FILE
export DEV_DEPLOYMENT_NAME=azuredeploy-1620258603816714800-dev
export MSYSTEM_CHOST=x86_64-w64-mingw32
export USERNAME=gillese
export DEPLOYMENT_SUFFIX=1620258603816714800
export ChocolateyInstall=C:\ProgramData\chocolatey
export LOGONSERVER=\\GILLESE11
export PROCESSOR_ARCHITECTURE=AMD64
export SP_DETAILS={
export   "appId": "06d5bd5c-580e-414a-934a-3f9611cf60ad",
export   "displayName": "azure-cli-2021-05-05-23-50-04",
export   "name": "http://azure-cli-2021-05-05-23-50-04",
export   "password": "2x5Ph3fqWatp-h0tpEcL_DbR3HUbI~EJtn",
export   "tenant": "11323e60-239d-49ea-b95e-09aeacca8eb9"
export }
export KUBERNETES_VERSION=1.19.9
export TENANT_ID=11323e60-239d-49ea-b95e-09aeacca8eb9
export LOCALAPPDATA=C:\Users\gillese\AppData\Local
export TYPE=PRECISION
export COMPUTERNAME=GILLESE11
export SYSTEMDRIVE=C:
export DELIVERY_PATH=.//src/shipping/delivery
export USERPROFILE=C:\Users\gillese
export DELIVERY_PRINCIPAL_RESOURCE_ID=/subscriptions/3759d480-6b3b-4ef6-920e-eb27803ab8e3/resourceGroups/geaz-msri-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/dev-d
export PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
export SYSTEMROOT=C:\Windows
export SP_OBJECT_ID=
export USERDOMAIN_ROAMINGPROFILE=MAGENIC
export OneDriveCommercial=C:\Users\gillese\OneDrive - Magenic
export PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 140 Stepping 1, GenuineIntel
export SSH_PUBLIC_KEY_FILE=C:\Users\gillese\.ssh\id_rsa.pub
export RESOURCE_GROUP=geaz-msri-rg
export MINGW_PACKAGE_PREFIX=mingw-w64-x86_64
export PWD=/c/users/gillese/training/microservices/microservices-reference-implementation
export SUBSCRIPTIONID=3759d480-6b3b-4ef6-920e-eb27803ab8e3
export SSH_ASKPASS=/mingw64/libexec/git-core/git-gui--askpass
export HOME=/c/Users/gillese
export WORKFLOW_ID_PRINCIPAL_ID=22159901-5ef5-4451-86c9-94db2ddd5a1c
export TMP=/tmp
export LC_CTYPE=en_US.UTF-8
export TERM_PROGRAM=mintty
export DEV_PREREQ_DEPLOYMENT_NAME=azuredeploy-prereqs-1620258603816714800-dev
export TERM_PROGRAM_VERSION=3.4.7
export DELIVERY_KEYVAULT_URI=https://dev-d-nopqttanbbbi2.vault.azure.net/
export MSYSTEM_PREFIX=/mingw64
export LOCATION=eastus2
export OneDrive=C:\Users\gillese\OneDrive - Magenic
export SERIAL=HSCLY93
export PROCESSOR_REVISION=8c01
export INGRESS_LOAD_BALANCER_IP_ID=/subscriptions/3759d480-6b3b-4ef6-920e-eb27803ab8e3/resourceGroups/rg-l3blgu7adyvui-nodepools/providers/Microsoft.Network/publicIPAddresses/kubernetes-a938cafc4dd39492fac9432fab7dfab7
export TMPDIR=/tmp
export DELIVERY_ID_PRINCIPAL_ID=5a91e6f5-43fa-4f15-8cdb-c0e2e69ecb67
export USERDNSDOMAIN=Magenic.net
export CHASSIS=Notebook
export DRONESCHEDULER_ID_NAME=dev-ds
export NUMBER_OF_PROCESSORS=8
export PROJECT_ROOT=./
export ProgramW6432=C:\Program Files
export DATABASE_NAME=dev-d-nopqttanbbbi2-db
export SP_CLIENT_SECRET=2x5Ph3fqWatp-h0tpEcL_DbR3HUbI~EJtn
export COMSPEC=C:\Windows\system32\cmd.exe
export APPDATA=C:\Users\gillese\AppData\Roaming
export TERM=xterm
export SHELL=/usr/bin/bash
export K8S=.//k8s
export COLLECTION_NAME=dev-d-nopqttanbbbi2-db-col
export EXTERNAL_INGEST_FQDN=geaz-msri-rg-ingest-dev.eastus2.cloudapp.azure.com
export WINDIR=C:\Windows
export AI_IKEY=8737d0db-cc6f-4631-b4c6-dbc9fdae0e75
export MINGW_CHOST=x86_64-w64-mingw32
export ProgramData=C:\ProgramData
export SHLVL=2
export PLINK_PROTOCOL=ssh
export PROGRAMFILES=C:\Program Files
export ACLOCAL_PATH=/mingw64/share/aclocal:/usr/share/aclocal
export MANPATH=/mingw64/local/man:/mingw64/share/man:/usr/local/man:/usr/share/man:/usr/man:/share/man
export ORIGINAL_TEMP=/tmp
export ORIGINAL_TMP=/tmp
export ALLUSERSPROFILE=C:\ProgramData
export TEMP=/tmp
export RESOURCE_GROUP_ACR=geaz-msri-rg-acr
export DriverData=C:\Windows\System32\Drivers\DriverData
export MSYSTEM=MINGW64
export SUBSCRIPTION_NAME=Windows Azure  MSDN - Visual Studio Premium
export MINGW_PREFIX=/mingw64
export DELIVERY_ID_NAME=dev-d
export DELIVERY_PRINCIPAL_CLIENT_ID=f9313bfd-fffc-4148-a27b-da3a5969c099
export ProgramFiles(x86)=C:\Program Files (x86)
export PATH=/c/Users/gillese/bin:/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/mingw64/bin:/usr/bin:/c/Users/gillese/bin:/c/Program Files (x86)/Microsoft SDKs/Azure/CLI2/wbin:/c/Windows/system32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0:/c/Windows/System32/OpenSSH:/c/ProgramData/chocolatey/bin:/cmd:/c/Program Files/Microsoft VS Code/bin:/c/Program Files/Docker/Docker/resources/bin:/c/ProgramData/DockerDesktop/version-bin:/c/Program Files/nodejs:/c/Program Files/dotnet:/c/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn:/c/Program Files (x86)/Microsoft SQL Server/150/Tools/Binn:/c/Program Files/Microsoft SQL Server/150/Tools/Binn:/c/Program Files/Microsoft SQL Server/150/DTS/Binn:/c/Program Files (x86)/Microsoft SQL Server/150/DTS/Binn:/c/Program Files/Azure Data Studio/bin:/c/Program Files/Microsoft SQL Server/130/Tools/Binn:/c/Users/gillese/AppData/Local/Microsoft/WindowsApps:/c/Users/gillese/AppData/Roaming/npm:/c/Users/gillese/.dotnet/tools:/c/Users/gillese/AppData/Local/Programs/Fiddler:/usr/bin/vendor_perl:/usr/bin/core_perl
export EXTERNAL_INGEST_DNS_NAME=geaz-msri-rg-ingest-dev
export HOMEDRIVE=C:
export PKG_CONFIG_PATH=/mingw64/lib/pkgconfig:/mingw64/share/pkgconfig
export AI_NAME=devwd7tekijg7uqe
export INFOPATH=/usr/local/info:/usr/share/info:/usr/info:/share/info
export ACR_NAME=i77tddxe3v5lw
export HOMEPATH=\Users\gillese
export CLUSTER_NAME=l3blgu7adyvui
export ORIGINAL_PATH=/mingw64/bin:/usr/bin:/c/Users/gillese/bin:/c/Program Files (x86)/Microsoft SDKs/Azure/CLI2/wbin:/c/Windows/system32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0:/c/Windows/System32/OpenSSH:/c/ProgramData/chocolatey/bin:/cmd:/c/Program Files/Microsoft VS Code/bin:/c/Program Files/Docker/Docker/resources/bin:/c/ProgramData/DockerDesktop/version-bin:/c/Program Files/nodejs:/c/Program Files/dotnet:/c/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn:/c/Program Files (x86)/Microsoft SQL Server/150/Tools/Binn:/c/Program Files/Microsoft SQL Server/150/Tools/Binn:/c/Program Files/Microsoft SQL Server/150/DTS/Binn:/c/Program Files (x86)/Microsoft SQL Server/150/DTS/Binn:/c/Program Files/Azure Data Studio/bin:/c/Program Files/Microsoft SQL Server/130/Tools/Binn:/c/Users/gillese/AppData/Local/Microsoft/WindowsApps:/c/Users/gillese/AppData/Roaming/npm:/c/Users/gillese/.dotnet/tools:/c/Users/gillese/AppData/Local/Programs/Fiddler
export SUBSCRIPTION_ID=3759d480-6b3b-4ef6-920e-eb27803ab8e3
export ASPNETCORE_ENVIRONMENT=Development
export DRONESCHEDULER_ID_PRINCIPAL_ID=1c8bce78-4eb6-45a4-8739-96270cdf0f46
export _=/usr/bin/printenv
