{{- if .Values.ingress.tls}}
{{- $relname := .Release.Name }}
{{- range .Values.ingress.tls.secrets }}
kind: Secret
apiVersion: v1
metadata:
  name: "delivery-ingress-tls"
type: kubernetes.io/tls
data:
  tls.crt: {{ .certificate | b64enc }}
  tls.key: {{ .key | b64enc }}
---
{{ end }}
{{ end }}
